data_dir: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/data"
samplesheet: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/Workflow-integrating-fragmentomics-and-ML-for-monitoring-cfDNA-analysis-in-NSCLC/config/samples.tsv"

reference:
  fasta: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.fa"
  bwa_index_prefix: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna"

reference_fa: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.fa"
gc_wig: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.gc.wig"
map_wig: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.map.wig"
bwa_extra: ""

threads_map: 8
threads_sort: 8
threads_markdup: 4
threads_cov: 2
threads_frag: 2
threads_ichor: 4

threads:
  align: 8
  markdup: 4
  cov: 2
  frag: 2
  ichor: 4

coverage_bins: 1000000

ichorcna:
  do_run: true
  ploidy: [2]
  normal: [0.5, 0.7, 0.9]
  maxCN: 5
  gc_wig: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.gc.wig"
  map_wig: "/lustre/fs0/storage/u812009/analysis/public_datasets/trypipeline/ref/hg38/hg38.map.wig"

fragmentomics:
  do_run: true
  length_min: 100
  length_max: 220

labels:
  cancer: "cancer"
  healthy: "healthy"

binsize_cna: 1000000

# --- required by Snakefile (top-level) ---
ploidy: [2]
normal: [0.5, 0.7, 0.9]
